name: 🚀 Deploy Discord Bot
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: 📦 Install dependencies
      run: npm install 
    - name: Install TypeScript
      run: npm i -g typescript
    - name: 🏗 Build
      run: tsc
    - name: Move package.json
      run: mv package.json ./dist/package.json
    - name: Add config
      run: |
        echo 'UNSPLASH_ACCESS_KEY="${{secrets.UNSPLASH_ACCESS_KEY}}"' >> dist/.env
        echo 'DISCORD_TOKEN="${{secrets.DISCORD_TOKEN}}"' >> ./dist/.env
        echo 'DB_USERNAME="${{secrets.DB_USERNAME}}"' >> ./dist/.env
        echo 'DB_PASSWORD="${{secrets.DB_PASSWORD}}"' >> ./dist/.env
        echo 'DATABASE="${{secrets.DATABASE}}"' >> ./dist/.env
    - name: 📂 Sync files
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: 'v-buf-29.sparkedhost.us'
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        localDir: 'dist'
        remoteDir: '/home/container'
        port: 2022