name: 🚀 Deploy website on push
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: 📦 Install dependencies
      run: npm install 
    - name: Install TypeScript
      run: npm i -g typescript
    - name: 🏗 Build
      run: tsc
    - name: Move package.json
      run: mv package.json ./dist/package.json
    - name: Add config
      run: |
        echo 'TOKEN="${{secrets.TOKEN}}"' >> ./dist/.env
        echo 'UNSPLASH_ACCESS_KEY="${{secrets.UNSPLASH_ACCESS_KEY}}' >> ./dist/.env
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v2.0.0
      with:
        method: sftp
        ftp_password: ${{secrets.PASSWORD}}
        ftp_server: ${{secrets.SERVER}}
        ftp_username: ${{secrets.USERNAME}}
        local_dir: dist
        port: 2022
        